### Site metadata ###
site_name: CaDoodle CAD
site_description: Documentation for CaDoodle CAD - A simple yet powerful CAD solution
site_url: https://cadoodlecad.com/
repo_url: https://github.com/CaDoodleWebsite/cadoodlecad.github.io
edit_uri: edit/master/docs/docs
### Build settings ###
theme: readthedocs
use_directory_urls: false  # Prevents redirects
docs_dir: docs  # Where your documentation files live
site_dir: site  # Where mkdocs will build the final site
extra:
  favicon: favicon.ico
nav:
  - About CaDoodle CAD: landing.md
  - History: tutorial/history.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
